[tasks.lint-toml]
description = "Run lint TOML files"
hide        = true
run         = "taplo format --check"

[tasks.fix-toml]
description = "Run fix TOML files"
hide        = true
run         = "taplo format"

[tools]
node             = "20.18.1"
"npm:@taplo/cli" = "0.7.0"
python           = "3.12.6"
terraform        = "1.12.2"
